import 'reflect-metadata'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function keyOf(word: string) {
  return word.trim().toLowerCase()
}

const cet4Words = [
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: '放弃；抛弃', example: 'Never abandon your dreams.' },
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: '能力；才能', example: 'She has the ability to succeed.' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', meaning: '在国外；到国外', example: 'He went abroad to study.' },
  { word: 'absent', phonetic: '/ˈæbsənt/', meaning: '缺席的；不在的', example: 'He was absent from school.' },
  { word: 'absorb', phonetic: '/əbˈsɔːrb/', meaning: '吸收；理解', example: 'Plants absorb water from the soil.' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: '抽象的；摘要', example: 'This is an abstract concept.' },
  { word: 'abundant', phonetic: '/əˈbʌndənt/', meaning: '丰富的；充裕的', example: 'The region has abundant resources.' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: '学术的；学院的', example: 'Academic performance is important.' },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: '加速；促进', example: 'The car began to accelerate.' },
  { word: 'accept', phonetic: '/əkˈsept/', meaning: '接受；承认', example: 'Please accept my apology.' },
  { word: 'access', phonetic: '/ˈækses/', meaning: '进入；通道', example: 'You need access to the system.' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', meaning: '事故；意外', example: 'A car accident happened here.' },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: '容纳；适应', example: 'The hotel can accommodate 500 guests.' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: '陪伴；伴随', example: 'He will accompany you home.' },
  { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: '完成；实现', example: 'We accomplished our goal.' },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: '准确的；精确的', example: 'The data is accurate.' },
  { word: 'accuse', phonetic: '/əˈkjuːz/', meaning: '指控；谴责', example: 'He was accused of theft.' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: '实现；达到', example: 'You can achieve your goals.' },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', meaning: '承认；感谢', example: 'I acknowledge my mistake.' },
  { word: 'acquire', phonetic: '/əˈkwaɪər/', meaning: '获得；学到', example: 'She acquired new skills.' },
  { word: 'adapt', phonetic: '/əˈdæpt/', meaning: '适应；改编', example: 'You must adapt to changes.' },
  { word: 'addition', phonetic: '/əˈdɪʃn/', meaning: '加法；增加', example: 'In addition, we need more time.' },
  { word: 'address', phonetic: '/əˈdres/', meaning: '地址；演说', example: 'What is your address?' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: '足够的；适当的', example: 'We have adequate resources.' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: '调整；适应', example: 'Please adjust the settings.' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', meaning: '管理；行政', example: 'The administration needs improvement.' },
  { word: 'admire', phonetic: '/ədˈmaɪər/', meaning: '钦佩；欣赏', example: 'I admire your courage.' },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: '承认；允许进入', example: 'He admitted his mistake.' },
  { word: 'adopt', phonetic: '/əˈdɒpt/', meaning: '采用；收养', example: 'They adopted a new policy.' },
  { word: 'adult', phonetic: '/ˈædʌlt/', meaning: '成年人；成年的', example: 'He is now an adult.' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning: '前进；进步', example: 'Technology continues to advance.' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: '优势；好处', example: 'This gives us an advantage.' },
  { word: 'adventure', phonetic: '/ədˈventʃər/', meaning: '冒险；奇遇', example: 'Life is an adventure.' },
  { word: 'advertise', phonetic: '/ˈædvətaɪz/', meaning: '做广告；宣传', example: 'They advertise on TV.' },
  { word: 'affair', phonetic: '/əˈfeər/', meaning: '事务；事件', example: 'It is a private affair.' },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: '影响；感动', example: 'The weather affects our plans.' },
  { word: 'afford', phonetic: '/əˈfɔːrd/', meaning: '负担得起；提供', example: 'I cannot afford this car.' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', meaning: '侵略的；有进取心的', example: 'He is an aggressive salesman.' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', meaning: '农业', example: 'Agriculture is important for economy.' },
  { word: 'aircraft', phonetic: '/ˈeəkrɑːft/', meaning: '飞机；航空器', example: 'The aircraft landed safely.' },
  { word: 'alarm', phonetic: '/əˈlɑːrm/', meaning: '警报；惊恐', example: 'The alarm went off.' },
  { word: 'alcohol', phonetic: '/ˈælkəhɒl/', meaning: '酒精；酒', example: 'Avoid drinking alcohol.' },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: '分配；拨出', example: 'We need to allocate resources.' },
  { word: 'allowance', phonetic: '/əˈlaʊəns/', meaning: '津贴；零用钱', example: 'He gets a weekly allowance.' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', meaning: '替代的；选择', example: 'We need an alternative plan.' },
  { word: 'amateur', phonetic: '/ˈæmətər/', meaning: '业余爱好者', example: 'He is an amateur photographer.' },
  { word: 'amaze', phonetic: '/əˈmeɪz/', meaning: '使惊奇', example: 'The news amazed everyone.' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: '雄心；野心', example: 'He has great ambition.' },
  { word: 'ambulance', phonetic: '/ˈæmbjələns/', meaning: '救护车', example: 'Call an ambulance!' },
  { word: 'amend', phonetic: '/əˈmend/', meaning: '修正；改进', example: 'We need to amend the law.' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', meaning: '数量；总计', example: 'A large amount of money.' },
  { word: 'analyse', phonetic: '/ˈænəlaɪz/', meaning: '分析', example: 'We need to analyse the data.' },
  { word: 'ancestor', phonetic: '/ˈænsestər/', meaning: '祖先', example: 'Our ancestors came from Africa.' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', meaning: '古代的；古老的', example: 'This is an ancient temple.' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', meaning: '角度；观点', example: 'Look at it from a different angle.' },
  { word: 'anniversary', phonetic: '/ˌænɪˈvɜːrsəri/', meaning: '周年纪念日', example: 'Happy anniversary!' },
  { word: 'announce', phonetic: '/əˈnaʊns/', meaning: '宣布；宣告', example: 'They announced the winner.' },
  { word: 'annual', phonetic: '/ˈænjuəl/', meaning: '每年的；年度的', example: 'This is our annual meeting.' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', meaning: '预期；期望', example: 'We anticipate good results.' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', meaning: '焦虑；担忧', example: 'She felt anxiety before the exam.' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', meaning: '焦虑的；渴望的', example: 'I am anxious about the result.' },
  { word: 'apparent', phonetic: '/əˈpærənt/', meaning: '明显的；表面的', example: 'The reason is apparent.' },
  { word: 'appeal', phonetic: '/əˈpiːl/', meaning: '呼吁；吸引', example: 'This idea appeals to me.' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', meaning: '食欲；胃口', example: 'I have a good appetite.' },
  { word: 'applaud', phonetic: '/əˈplɔːd/', meaning: '鼓掌；称赞', example: 'The audience applauded.' },
  { word: 'applicable', phonetic: '/əˈplɪkəbl/', meaning: '适用的；可应用的', example: 'This rule is applicable here.' },
  { word: 'applicant', phonetic: '/ˈæplɪkənt/', meaning: '申请人', example: 'All applicants must submit forms.' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', meaning: '申请；应用', example: 'Submit your application.' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', meaning: '任命；指定', example: 'He was appointed manager.' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', meaning: '欣赏；感激', example: 'I appreciate your help.' },
  { word: 'approach', phonetic: '/əˈprəʊtʃ/', meaning: '接近；方法', example: 'We need a new approach.' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: '适当的；恰当的', example: 'Wear appropriate clothing.' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: '批准；赞成', example: 'I approve of your plan.' },
  { word: 'approximate', phonetic: '/əˈprɒksɪmət/', meaning: '大约的；近似的', example: 'The approximate cost is $100.' },
  { word: 'arbitrary', phonetic: '/ˈɑːrbɪtrəri/', meaning: '任意的；武断的', example: 'This is an arbitrary decision.' },
  { word: 'architect', phonetic: '/ˈɑːrkɪtekt/', meaning: '建筑师', example: 'He is a famous architect.' },
  { word: 'argue', phonetic: '/ˈɑːrɡjuː/', meaning: '争论；辩论', example: 'They argue about politics.' },
  { word: 'arise', phonetic: '/əˈraɪz/', meaning: '出现；产生', example: 'Problems may arise.' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: '安排；整理', example: 'I will arrange a meeting.' },
  { word: 'arrest', phonetic: '/əˈrest/', meaning: '逮捕；阻止', example: 'The police arrested him.' },
  { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃl/', meaning: '人工的；人造的', example: 'This is artificial intelligence.' },
  { word: 'aspect', phonetic: '/ˈæspekt/', meaning: '方面；外观', example: 'Consider every aspect.' },
  { word: 'assemble', phonetic: '/əˈsembl/', meaning: '集合；组装', example: 'Please assemble in the hall.' },
  { word: 'assess', phonetic: '/əˈses/', meaning: '评估；评定', example: 'We need to assess the situation.' },
  { word: 'assign', phonetic: '/əˈsaɪn/', meaning: '分配；指派', example: 'The teacher assigned homework.' },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: '帮助；协助', example: 'Can I assist you?' },
  { word: 'associate', phonetic: '/əˈsəʊʃieɪt/', meaning: '联想；交往', example: 'I associate this song with summer.' },
  { word: 'assume', phonetic: '/əˈsjuːm/', meaning: '假设；承担', example: 'Let us assume this is true.' },
  { word: 'assure', phonetic: '/əˈʃʊər/', meaning: '保证；确保', example: 'I assure you it is safe.' },
  { word: 'astonish', phonetic: '/əˈstɒnɪʃ/', meaning: '使惊讶', example: 'The news astonished me.' },
  { word: 'athlete', phonetic: '/ˈæθliːt/', meaning: '运动员', example: 'He is a professional athlete.' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪər/', meaning: '大气；气氛', example: 'The atmosphere was friendly.' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: '附上；贴上', example: 'Please attach your resume.' },
  { word: 'attain', phonetic: '/əˈteɪn/', meaning: '获得；达到', example: 'He attained his goal.' },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: '尝试；企图', example: 'He made an attempt to help.' },
  { word: 'attend', phonetic: '/əˈtend/', meaning: '参加；照料', example: 'Please attend the meeting.' },
  { word: 'attitude', phonetic: '/ˈætɪtjuːd/', meaning: '态度；看法', example: 'Your attitude is important.' },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: '吸引', example: 'The music attracted a crowd.' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', meaning: '归因于；属性', example: 'He attributes his success to hard work.' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', meaning: '观众；听众', example: 'The audience clapped.' },
  { word: 'authority', phonetic: '/ɔːˈθɒrəti/', meaning: '权威；当局', example: 'The local authority decided.' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', meaning: '自动的', example: 'This is an automatic door.' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: '可用的；有空的', example: 'Is this seat available?' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: '平均的；普通的', example: 'The average score was 75.' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: '避免；躲避', example: 'Avoid making mistakes.' },
  { word: 'award', phonetic: '/əˈwɔːrd/', meaning: '奖；奖品', example: 'He won an award.' },
  { word: 'aware', phonetic: '/əˈweər/', meaning: '意识到的；知道的', example: 'Be aware of the danger.' },
  { word: 'awful', phonetic: '/ˈɔːfl/', meaning: '可怕的；糟糕的', example: 'The weather was awful.' },
  { word: 'awkward', phonetic: '/ˈɔːkwərd/', meaning: '笨拙的；尴尬的', example: 'It was an awkward situation.' },
]

const cet6Words = [
  { word: 'abnormal', phonetic: '/æbˈnɔːrml/', meaning: '反常的；变态的', example: 'This behavior is abnormal.' },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', meaning: '废除；取消', example: 'They abolished the old law.' },
  { word: 'abrupt', phonetic: '/əˈbrʌpt/', meaning: '突然的；唐突的', example: 'There was an abrupt change.' },
  { word: 'absurd', phonetic: '/əbˈsɜːrd/', meaning: '荒谬的；可笑的', example: 'This idea is absurd.' },
  { word: 'abundance', phonetic: '/əˈbʌndəns/', meaning: '丰富；充裕', example: 'There is an abundance of food.' },
  { word: 'accommodation', phonetic: '/əˌkɒməˈdeɪʃn/', meaning: '住宿；适应', example: 'We need accommodation for tonight.' },
  { word: 'accordance', phonetic: '/əˈkɔːrdns/', meaning: '一致；按照', example: 'In accordance with the rules.' },
  { word: 'acknowledgement', phonetic: '/əkˈnɒlɪdʒmənt/', meaning: '承认；感谢', example: 'We received an acknowledgement.' },
  { word: 'acquaintance', phonetic: '/əˈkweɪntəns/', meaning: '熟人；了解', example: 'He is an acquaintance of mine.' },
  { word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', meaning: '获得；收购', example: 'The acquisition was successful.' },
  { word: 'adaptive', phonetic: '/əˈdæptɪv/', meaning: '适应的；有适应性的', example: 'Humans are adaptive creatures.' },
  { word: 'addict', phonetic: '/ˈædɪkt/', meaning: '上瘾者；使上瘾', example: 'He is a drug addict.' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: '充分的；足够的', example: 'We have adequate supplies.' },
  { word: 'adhere', phonetic: '/ədˈhɪər/', meaning: '坚持；粘附', example: 'You must adhere to the rules.' },
  { word: 'adjacent', phonetic: '/əˈdʒeɪsnt/', meaning: '邻近的；毗连的', example: 'The adjacent building is old.' },
  { word: 'adjoin', phonetic: '/əˈdʒɔɪn/', meaning: '贴近；毗连', example: 'The two rooms adjoin.' },
  { word: 'adjustable', phonetic: '/əˈdʒʌstəbl/', meaning: '可调整的', example: 'This chair is adjustable.' },
  { word: 'administer', phonetic: '/ədˈmɪnɪstər/', meaning: '管理；执行', example: 'He administers the department.' },
  { word: 'adolescent', phonetic: '/ˌædəˈlesnt/', meaning: '青少年', example: 'Adolescents need guidance.' },
  { word: 'advent', phonetic: '/ˈædvent/', meaning: '出现；到来', example: 'The advent of the internet changed everything.' },
  { word: 'adverse', phonetic: '/ˈædvɜːrs/', meaning: '不利的；有害的', example: 'Adverse weather conditions.' },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: '提倡；支持者', example: 'He advocates for human rights.' },
  { word: 'aerial', phonetic: '/ˈeəriəl/', meaning: '空中的；天线', example: 'An aerial view of the city.' },
  { word: 'aesthetic', phonetic: '/iːsˈθetɪk/', meaning: '美学的；审美的', example: 'The aesthetic value is high.' },
  { word: 'affiliate', phonetic: '/əˈfɪlieɪt/', meaning: '附属；使加入', example: 'This company is an affiliate.' },
  { word: 'affirm', phonetic: '/əˈfɜːrm/', meaning: '断言；确认', example: 'He affirmed his commitment.' },
  { word: 'afflict', phonetic: '/əˈflɪkt/', meaning: '折磨；使痛苦', example: 'The disease afflicts many people.' },
  { word: 'agenda', phonetic: '/əˈdʒendə/', meaning: '议程；日程', example: 'What is on the agenda?' },
  { word: 'aggravate', phonetic: '/ˈæɡrəveɪt/', meaning: '加重；恶化', example: 'This will aggravate the situation.' },
  { word: 'aggregate', phonetic: '/ˈæɡrɪɡət/', meaning: '总计；合计', example: 'The aggregate score was 90.' },
  { word: 'agitate', phonetic: '/ˈædʒɪteɪt/', meaning: '煽动；搅动', example: 'They agitated for change.' },
  { word: 'alienate', phonetic: '/ˈeɪliəneɪt/', meaning: '疏远；使疏远', example: 'His behavior alienated his friends.' },
  { word: 'allegedly', phonetic: '/əˈledʒɪdli/', meaning: '据说；据称', example: 'He is allegedly the thief.' },
  { word: 'alleviate', phonetic: '/əˈliːvieɪt/', meaning: '减轻；缓解', example: 'This medicine alleviates pain.' },
  { word: 'alliance', phonetic: '/əˈlaɪəns/', meaning: '联盟；同盟', example: 'They formed an alliance.' },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: '分配；拨给', example: 'Funds were allocated for the project.' },
  { word: 'allowance', phonetic: '/əˈlaʊəns/', meaning: '津贴；零用钱', example: 'He receives a monthly allowance.' },
  { word: 'ally', phonetic: '/ˈælaɪ/', meaning: '盟友；同盟国', example: 'They are close allies.' },
  { word: 'alongside', phonetic: '/əˌlɒŋˈsaɪd/', meaning: '在旁边；与...并肩', example: 'He walked alongside her.' },
  { word: 'alternate', phonetic: '/ɔːlˈtɜːrnət/', meaning: '交替的；轮流的', example: 'We meet on alternate days.' },
  { word: 'amateur', phonetic: '/ˈæmətər/', meaning: '业余爱好者', example: 'He is an amateur painter.' },
  { word: 'ambassador', phonetic: '/æmˈbæsədər/', meaning: '大使', example: 'He is the ambassador to France.' },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: '模糊的；有歧义的', example: 'The statement was ambiguous.' },
  { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', meaning: '有雄心的；野心勃勃的', example: 'She is an ambitious woman.' },
  { word: 'amend', phonetic: '/əˈmend/', meaning: '修正；改进', example: 'The law was amended.' },
  { word: 'ammunition', phonetic: '/ˌæmjəˈnɪʃn/', meaning: '弹药；军火', example: 'They ran out of ammunition.' },
  { word: 'ample', phonetic: '/ˈæmpl/', meaning: '充足的；宽敞的', example: 'We have ample time.' },
  { word: 'amplify', phonetic: '/ˈæmplɪfaɪ/', meaning: '放大；增强', example: 'Please amplify your point.' },
  { word: 'analogy', phonetic: '/əˈnælədʒi/', meaning: '类比；相似', example: 'Draw an analogy between them.' },
  { word: 'analytic', phonetic: '/ˌænəˈlɪtɪk/', meaning: '分析的；解析的', example: 'He has an analytic mind.' },
  { word: 'angel', phonetic: '/ˈeɪndʒl/', meaning: '天使', example: 'She is like an angel.' },
  { word: 'annoyance', phonetic: '/əˈnɔɪəns/', meaning: '烦恼；恼怒', example: 'His annoyance was obvious.' },
  { word: 'anonymous', phonetic: '/əˈnɒnɪməs/', meaning: '匿名的', example: 'The donor was anonymous.' },
  { word: 'antique', phonetic: '/ænˈtiːk/', meaning: '古董；古老的', example: 'This is an antique vase.' },
  { word: 'apologize', phonetic: '/əˈpɒlədʒaɪz/', meaning: '道歉', example: 'I apologize for being late.' },
  { word: 'apparatus', phonetic: '/ˌæpəˈreɪtəs/', meaning: '仪器；设备', example: 'The laboratory apparatus.' },
  { word: 'appease', phonetic: '/əˈpiːz/', meaning: '安抚；平息', example: 'They tried to appease him.' },
  { word: 'appendix', phonetic: '/əˈpendɪks/', meaning: '附录；阑尾', example: 'See the appendix for details.' },
  { word: 'applause', phonetic: '/əˈplɔːz/', meaning: '鼓掌；喝彩', example: 'The audience gave applause.' },
  { word: 'appliance', phonetic: '/əˈplaɪəns/', meaning: '器具；电器', example: 'Home appliances are expensive.' },
  { word: 'applicable', phonetic: '/əˈplɪkəbl/', meaning: '适用的；可应用的', example: 'This rule is not applicable.' },
  { word: 'appraisal', phonetic: '/əˈpreɪzl/', meaning: '评价；估价', example: 'The appraisal was positive.' },
  { word: 'appreciable', phonetic: '/əˈpriːʃəbl/', meaning: '可观的；明显的', example: 'There was appreciable improvement.' },
  { word: 'apprehend', phonetic: '/ˌæprɪˈhend/', meaning: '逮捕；理解', example: 'The police apprehended the suspect.' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: '适当的；挪用', example: 'This is appropriate behavior.' },
  { word: 'apt', phonetic: '/æpt/', meaning: '恰当的；易于...的', example: 'He is apt to forget things.' },
  { word: 'arbitrary', phonetic: '/ˈɑːrbɪtrəri/', meaning: '任意的；专断的', example: 'This is an arbitrary choice.' },
  { word: 'arc', phonetic: '/ɑːrk/', meaning: '弧；弧形', example: 'The rainbow formed an arc.' },
  { word: 'arch', phonetic: '/ɑːrtʃ/', meaning: '拱门；拱形', example: 'They walked through the arch.' },
  { word: 'arena', phonetic: '/əˈriːnə/', meaning: '竞技场；舞台', example: 'The political arena is challenging.' },
  { word: 'aristocrat', phonetic: '/ˈærɪstəkræt/', meaning: '贵族', example: 'He was born an aristocrat.' },
  { word: 'armor', phonetic: '/ˈɑːrmər/', meaning: '盔甲；装甲', example: 'The knight wore armor.' },
  { word: 'aroma', phonetic: '/əˈrəʊmə/', meaning: '香气；芳香', example: 'The aroma of coffee filled the room.' },
  { word: 'array', phonetic: '/əˈreɪ/', meaning: '排列；一系列', example: 'An array of options is available.' },
  { word: 'arrogant', phonetic: '/ˈærəɡənt/', meaning: '傲慢的；自大的', example: 'He is an arrogant person.' },
  { word: 'artery', phonetic: '/ˈɑːrtəri/', meaning: '动脉；干线', example: 'The main artery was blocked.' },
  { word: 'articulate', phonetic: '/ɑːrˈtɪkjələt/', meaning: '清晰表达；关节连接的', example: 'He articulated his ideas clearly.' },
  { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃl/', meaning: '人工的；虚伪的', example: 'Artificial flowers look real.' },
  { word: 'artillery', phonetic: '/ɑːrˈtɪləri/', meaning: '大炮；炮兵', example: 'The artillery fired.' },
  { word: 'ascend', phonetic: '/əˈsend/', meaning: '上升；攀登', example: 'He ascended the throne.' },
  { word: 'ascertain', phonetic: '/ˌæsərˈteɪn/', meaning: '查明；确定', example: 'We need to ascertain the facts.' },
  { word: 'ascribe', phonetic: '/əˈskraɪb/', meaning: '归因于', example: 'He ascribed his success to luck.' },
  { word: 'ashore', phonetic: '/əˈʃɔːr/', meaning: '在岸上；向岸上', example: 'They went ashore.' },
  { word: 'aspiration', phonetic: '/ˌæspəˈreɪʃn/', meaning: '抱负；渴望', example: 'He has high aspirations.' },
  { word: 'assassination', phonetic: '/əˌsæsɪˈneɪʃn/', meaning: '暗杀', example: 'The assassination shocked the world.' },
  { word: 'assault', phonetic: '/əˈsɔːlt/', meaning: '攻击；袭击', example: 'He was charged with assault.' },
  { word: 'assert', phonetic: '/əˈsɜːrt/', meaning: '断言；坚持', example: 'He asserted his rights.' },
  { word: 'assimilate', phonetic: '/əˈsɪməleɪt/', meaning: '吸收；同化', example: 'Immigrants assimilate into society.' },
  { word: 'assurance', phonetic: '/əˈʃʊərəns/', meaning: '保证；自信', example: 'He spoke with assurance.' },
  { word: 'astronomy', phonetic: '/əˈstrɒnəmi/', meaning: '天文学', example: 'He studies astronomy.' },
  { word: 'athlete', phonetic: '/ˈæθliːt/', meaning: '运动员', example: 'She is a professional athlete.' },
  { word: 'atlas', phonetic: '/ˈætləs/', meaning: '地图集', example: 'Look at the world atlas.' },
  { word: 'atom', phonetic: '/ˈætəm/', meaning: '原子', example: 'Everything is made of atoms.' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: '附上；依恋', example: 'Attach the file to the email.' },
  { word: 'attain', phonetic: '/əˈteɪn/', meaning: '达到；获得', example: 'He attained his goal.' },
]

async function main() {
  const books = [
    { code: 'CET4', name: 'CET-4（四级）词库', words: cet4Words },
    { code: 'CET6', name: 'CET-6（六级）词库', words: cet6Words },
  ] as const

  for (const b of books) {
    const book = await prisma.book.upsert({
      where: { code: b.code },
      create: { code: b.code, name: b.name },
      update: { name: b.name },
    })

    for (const w of b.words) {
      await prisma.word.upsert({
        where: { bookId_wordKey: { bookId: book.id, wordKey: keyOf(w.word) } },
        create: {
          bookId: book.id,
          word: w.word,
          wordKey: keyOf(w.word),
          phonetic: w.phonetic,
          meaning: w.meaning,
          example: w.example,
        },
        update: {
          word: w.word,
          phonetic: w.phonetic,
          meaning: w.meaning,
          example: w.example,
        },
      })
    }

    const count = await prisma.word.count({ where: { bookId: book.id } })
    console.log(`词库就绪：${b.code} ${b.name}（${count} 个）`)
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
